Swagger: '2.0'
tags:
  - name: Test API Swagger
get:
  - description: None
response:
  - '200':
    description: Succesful Response
  - '400':
    description: Bad Request
  - '500':
    description: Server Error
parameters:
  - name: name
    in: query
    type: string
    example: budi
  - name: nomerHp
    in: query
    type: string
    example: "078994"